- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~']

- shell:
  -
    command: zsh .prezto
    description: Installing Prezto.
    stdout: true
    stderr: true
  -
    command: sh .vundle
    description: Installing Vundle.
    stdout: true
    stderr: true

- link:
    ~/.zlogin:
    ~/.zlogout:
    ~/.zprofile:
    ~/.zshenv:
    ~/.zshrc:
    ~/.zpreztorc:
    ~/.streamlinkrc:
    ~/.wgetrc:
    ~/.vimrc:
    ~/.gitconfig:
    /usr/local/bin/imgcat:
      path: bin/imgcat
    /usr/local/bin/+x:
      path: bin/+x
    /usr/local/bin/lc:
      path: bin/lc

- shell:
  - [chmod +x /usr/local/bin/imgcat, Setting permissions for imgcat.]
  - [chmod +x /usr/local/bin/+x, Setting permissions for +x.]
  - [chmod +x /usr/local/bin/lc, Setting permissions for lc.]
  - [vim +PluginInstall +qall, Installing Vim plugins.]
